name = "tigerslair-academy"
main = "worker/src/index.js"
compatibility_date = "2026-08-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
PAYSTACK_SECRET_KEY = "sk_live_YOUR_ACTUAL_LIVE_PAYSTACK_SECRET_KEY_HERE"
BOT_TOKEN = "8954408184:AAEQ5fXqqQDvVa6IkXOqGKUPhdkCGB471Eo"

# Run the scheduled function once a day at 2:00 AM UTC (3:00 AM WAT)
[triggers]
crons = ["0 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tigerslair-db"
database_id = "0ab76b65-3e86-41aa-90f5-9196dae9772d"