name = "tigerslair-academy"
main = "worker/src/index.js"
compatibility_date = "2026-08-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
PAYSTACK_SECRET_KEY = "sk_live_YOUR_ACTUAL_LIVE_PAYSTACK_SECRET_KEY_HERE"
BOT_TOKEN = "8954408184:AAEQ5fXqqQDvVa6IkXOqGKUPhdkCGB471Eo"
BOT_USERNAME = "jsagebutlerbot"
ADMIN_CHANNEL_ID = "-1004315180917"      # your private admin channel/chat id
ADMIN_IDS = "784512390"                   # comma-separated numeric TG ids of admins
MINI_APP_URL = "https://t.me/jsagebutlerbot/TigersLairAcademy"
SITE_URL = "https://tigerslair-api.ehisferguson.workers.dev/"
TG_WEBHOOK_SECRET = "a-long-random-string-here"
[triggers]
crons = ["0 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tigerslair-db"
database_id = "0ab76b65-3e86-41aa-90f5-9196dae9772d"

# --- TEMPORARILY COMMENTED OUT UNTIL R2 BUCKET IS CREATED ---
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "tigerslair-resources"
